// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZW3H1w4wlqZT_i0CS9h3HfHicKipUr0I',
    appId: '1:95320653874:web:5dce87c284ef8f226f3c2b',
    messagingSenderId: '95320653874',
    projectId: 'todo-ddcbd',
    authDomain: 'todo-ddcbd.firebaseapp.com',
    storageBucket: 'todo-ddcbd.appspot.com',
    measurementId: 'G-4MKKPWZ4Y4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPHA94z5AAkGg05-O9Iy08qPiagDZLmf8',
    appId: '1:95320653874:android:f29cda93be1c822c6f3c2b',
    messagingSenderId: '95320653874',
    projectId: 'todo-ddcbd',
    storageBucket: 'todo-ddcbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAd18ewfGViCphDxbpOa5SussK0mxOUe8',
    appId: '1:95320653874:ios:c501cdc6184a31f16f3c2b',
    messagingSenderId: '95320653874',
    projectId: 'todo-ddcbd',
    storageBucket: 'todo-ddcbd.appspot.com',
    iosClientId:
        '95320653874-tesvpj4pe72jtsbrpcneput1mgn2n319.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAd18ewfGViCphDxbpOa5SussK0mxOUe8',
    appId: '1:95320653874:ios:c501cdc6184a31f16f3c2b',
    messagingSenderId: '95320653874',
    projectId: 'todo-ddcbd',
    storageBucket: 'todo-ddcbd.appspot.com',
    iosClientId:
        '95320653874-tesvpj4pe72jtsbrpcneput1mgn2n319.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
